// THIS FILE IS AUTOGENERATED. DO NOT EDIT.
import { Driver as DataResult } from '@/data/sim/formulaDrivers/driverDataTypes';
const result: DataResult[] = [
    {
        "driverDetails": {
            "uuid": "c41f3434-ef94-4d31-9eed-4fdc3f6cb876",
            "givenName": "Max",
            "familyName": "Verstappen",
            "familyNameFirst": false,
            "fullName": "Max Verstappen",
            "routePart": "max-verstappen-c41f3434"
        }
    },
    {
        "driverDetails": {
            "uuid": "8f4909bf-8859-44af-9b8d-f254cc5fa1b9",
            "givenName": "Charles",
            "familyName": "Leclerc",
            "familyNameFirst": false,
            "fullName": "Charles Leclerc",
            "routePart": "charles-leclerc-8f4909bf"
        }
    },
    {
        "driverDetails": {
            "uuid": "b6683cdd-6246-402f-8d63-673941252343",
            "givenName": "Sergio",
            "familyName": "Pérez",
            "familyNameFirst": false,
            "fullName": "Sergio Pérez",
            "routePart": "sergio-perez-b6683cdd"
        }
    },
    {
        "driverDetails": {
            "uuid": "0e1212d1-6b6c-4f47-8608-3012407b9868",
            "givenName": "George",
            "familyName": "Russell",
            "familyNameFirst": false,
            "fullName": "George Russell",
            "routePart": "george-russell-0e1212d1"
        }
    },
    {
        "driverDetails": {
            "uuid": "865a73e7-b8dc-4e10-916a-9764770a135c",
            "givenName": "Carlos",
            "familyName": "Sainz",
            "familyNameFirst": false,
            "fullName": "Carlos Sainz",
            "routePart": "carlos-sainz-865a73e7"
        }
    },
    {
        "driverDetails": {
            "uuid": "ea131eb5-ec03-4279-83fc-956ad94bd299",
            "givenName": "Lewis",
            "familyName": "Hamilton",
            "familyNameFirst": false,
            "fullName": "Lewis Hamilton",
            "routePart": "lewis-hamilton-ea131eb5"
        }
    },
    {
        "driverDetails": {
            "uuid": "6a9126c7-6e35-4cec-8fe5-d5e01fe3a466",
            "givenName": "Lando",
            "familyName": "Norris",
            "familyNameFirst": false,
            "fullName": "Lando Norris",
            "routePart": "lando-norris-6a9126c7"
        }
    },
    {
        "driverDetails": {
            "uuid": "d25ead1a-75a9-4626-9ca3-b83cdccdc1d9",
            "givenName": "Esteban",
            "familyName": "Ocon",
            "familyNameFirst": false,
            "fullName": "Esteban Ocon",
            "routePart": "esteban-ocon-d25ead1a"
        }
    },
    {
        "driverDetails": {
            "uuid": "cd4c1d0d-1f49-4429-871e-1c4a81e2cf74",
            "givenName": "Fernando",
            "familyName": "Alonso",
            "familyNameFirst": false,
            "fullName": "Fernando Alonso",
            "routePart": "fernando-alonso-cd4c1d0d"
        }
    },
    {
        "driverDetails": {
            "uuid": "d0813ed5-e64b-4d13-af20-fdaac3c6dbc7",
            "givenName": "Valtteri",
            "familyName": "Bottas",
            "familyNameFirst": false,
            "fullName": "Valtteri Bottas",
            "routePart": "valtteri-bottas-d0813ed5"
        }
    },
    {
        "driverDetails": {
            "uuid": "219f59ac-c0c8-4886-92ef-9bf806a94767",
            "givenName": "Daniel",
            "familyName": "Ricciardo",
            "familyNameFirst": false,
            "fullName": "Daniel Ricciardo",
            "routePart": "daniel-ricciardo-219f59ac"
        }
    },
    {
        "driverDetails": {
            "uuid": "245444c2-533b-4ab2-8d7c-518c09f4b479",
            "givenName": "Sebastian",
            "familyName": "Vettel",
            "familyNameFirst": false,
            "fullName": "Sebastian Vettel",
            "routePart": "sebastian-vettel-245444c2"
        }
    },
    {
        "driverDetails": {
            "uuid": "1b2846f5-0613-4725-bb40-cbcf6283fadd",
            "givenName": "Kevin",
            "familyName": "Magnussen",
            "familyNameFirst": false,
            "fullName": "Kevin Magnussen",
            "routePart": "kevin-magnussen-1b2846f5"
        }
    },
    {
        "driverDetails": {
            "uuid": "f3d27a10-c446-4c44-a0a7-dbf8f937058b",
            "givenName": "Pierre",
            "familyName": "Gasly",
            "familyNameFirst": false,
            "fullName": "Pierre Gasly",
            "routePart": "pierre-gasly-f3d27a10"
        }
    },
    {
        "driverDetails": {
            "uuid": "a0e93a44-0b90-4f18-a37b-edec16f1d21b",
            "givenName": "Lance",
            "familyName": "Stroll",
            "familyNameFirst": false,
            "fullName": "Lance Stroll",
            "routePart": "lance-stroll-a0e93a44"
        }
    },
    {
        "driverDetails": {
            "uuid": "e6263917-bd03-401c-85dc-5310b1923412",
            "givenName": "Mick",
            "familyName": "Schumacher",
            "familyNameFirst": false,
            "fullName": "Mick Schumacher",
            "routePart": "mick-schumacher-e6263917"
        }
    },
    {
        "driverDetails": {
            "uuid": "8de49864-f75f-4cd6-abb4-0771d2c72a1f",
            "givenName": "Yūki",
            "familyName": "Tsunoda",
            "familyNameFirst": true,
            "fullName": "Tsunoda Yūki",
            "routePart": "tsunoda-yuki-8de49864"
        }
    },
    {
        "driverDetails": {
            "uuid": "6ceac234-f995-4328-b1bb-289f5f4ad142",
            "givenName": "Guànyǔ",
            "familyName": "Zhōu",
            "familyNameFirst": true,
            "fullName": "Zhōu Guànyǔ",
            "routePart": "zhou-guanyu-6ceac234"
        }
    },
    {
        "driverDetails": {
            "uuid": "94f92728-556c-405c-b18a-eed2f9138c78",
            "givenName": "Alexander",
            "familyName": "Albon",
            "familyNameFirst": false,
            "fullName": "Alexander Albon",
            "routePart": "alexander-albon-94f92728"
        }
    },
    {
        "driverDetails": {
            "uuid": "ef19af25-7750-4311-8049-2994c9edad0b",
            "givenName": "Nicholas",
            "familyName": "Latifi",
            "familyNameFirst": false,
            "fullName": "Nicholas Latifi",
            "routePart": "nicholas-latifi-ef19af25"
        }
    },
    {
        "driverDetails": {
            "uuid": "41e6b7c4-b0a8-4a61-9b24-16bea1b84404",
            "givenName": "Nyck",
            "familyName": "de Vries",
            "familyNameFirst": false,
            "fullName": "Nyck de Vries",
            "routePart": "nyck-de vries-41e6b7c4"
        }
    },
    {
        "driverDetails": {
            "uuid": "fce0b388-3a0d-4d46-af1d-0a744b73f746",
            "givenName": "Nico",
            "familyName": "Hülkenberg",
            "familyNameFirst": false,
            "fullName": "Nico Hülkenberg",
            "routePart": "nico-hulkenberg-fce0b388"
        }
    },
    {
        "driverDetails": {
            "uuid": "3bc7a1e7-a088-4993-9579-edcd5ada769a",
            "givenName": "Kimi",
            "familyName": "Räikkönen",
            "familyNameFirst": false,
            "fullName": "Kimi Räikkönen",
            "routePart": "kimi-raikkonen-3bc7a1e7"
        }
    },
    {
        "driverDetails": {
            "uuid": "11a834ee-dbc9-41af-a92c-1b7d5b17ec86",
            "givenName": "Nikita",
            "familyName": "Mazepin",
            "familyNameFirst": false,
            "fullName": "Nikita Mazepin",
            "routePart": "nikita-mazepin-11a834ee"
        }
    },
    {
        "driverDetails": {
            "uuid": "71d45ec8-9e0f-46c4-a399-d0905bfae8e4",
            "givenName": "Antonio",
            "familyName": "Giovinazzi",
            "familyNameFirst": false,
            "fullName": "Antonio Giovinazzi",
            "routePart": "antonio-giovinazzi-71d45ec8"
        }
    },
    {
        "driverDetails": {
            "uuid": "c28dac31-eda3-4084-a10a-0ecc5c975678",
            "givenName": "Robert",
            "familyName": "Kubica",
            "familyNameFirst": false,
            "fullName": "Robert Kubica",
            "routePart": "robert-kubica-c28dac31"
        }
    },
    {
        "driverDetails": {
            "uuid": "85d6383f-2a59-4e66-85d6-80f573ade1fa",
            "givenName": "Oscar",
            "familyName": "Piastri",
            "familyNameFirst": false,
            "fullName": "Oscar Piastri",
            "routePart": "oscar-piastri-85d6383f"
        }
    },
    {
        "driverDetails": {
            "uuid": "7bb2c22c-56b2-4be2-85bb-697cb7c7b5da",
            "givenName": "Logan",
            "familyName": "Sargeant",
            "familyNameFirst": false,
            "fullName": "Logan Sargeant",
            "routePart": "logan-sargeant-7bb2c22c"
        }
    },
    {
        "driverDetails": {
            "uuid": "0807b2fd-9090-45c9-af7c-daec36b2e283",
            "givenName": "Daniil",
            "familyName": "Kvyat",
            "familyNameFirst": false,
            "fullName": "Daniil Kvyat",
            "routePart": "daniil-kvyat-0807b2fd"
        }
    },
    {
        "driverDetails": {
            "uuid": "6b04dfbe-f6c6-4ebd-9a63-557e3bb587bb",
            "givenName": "Romain",
            "familyName": "Grosjean",
            "familyNameFirst": false,
            "fullName": "Romain Grosjean",
            "routePart": "romain-grosjean-6b04dfbe"
        }
    },
    {
        "driverDetails": {
            "uuid": "1cc90a6a-55a0-4403-8f6b-8ece5a4a4800",
            "givenName": "Pietro",
            "familyName": "Fittipaldi",
            "familyNameFirst": false,
            "fullName": "Pietro Fittipaldi",
            "routePart": "pietro-fittipaldi-1cc90a6a"
        }
    },
    {
        "driverDetails": {
            "uuid": "af0027d6-56e3-46d4-9f31-924940fa3a1c",
            "givenName": "Jack",
            "familyName": "Aitken",
            "familyNameFirst": false,
            "fullName": "Jack Aitken",
            "routePart": "jack-aitken-af0027d6"
        }
    },
    {
        "driverDetails": {
            "uuid": "93ea0728-d68c-49ed-b758-12d69854ee7b",
            "givenName": "Stoffel",
            "familyName": "Vandoorne",
            "familyNameFirst": false,
            "fullName": "Stoffel Vandoorne",
            "routePart": "stoffel-vandoorne-93ea0728"
        }
    },
    {
        "driverDetails": {
            "uuid": "5d70e4da-209f-46a7-88de-f72ab10cd5ed",
            "givenName": "Marcus",
            "familyName": "Ericsson",
            "familyNameFirst": false,
            "fullName": "Marcus Ericsson",
            "routePart": "marcus-ericsson-5d70e4da"
        }
    },
    {
        "driverDetails": {
            "uuid": "e93da3ea-1cd7-4a3b-89a6-a08abb10df17",
            "givenName": "Brendon",
            "familyName": "Hartley",
            "familyNameFirst": false,
            "fullName": "Brendon Hartley",
            "routePart": "brendon-hartley-e93da3ea"
        }
    },
    {
        "driverDetails": {
            "uuid": "80144f7a-8e6d-45ca-88f6-823d83c39eff",
            "givenName": "Sergey",
            "familyName": "Sirotkin",
            "familyNameFirst": false,
            "fullName": "Sergey Sirotkin",
            "routePart": "sergey-sirotkin-80144f7a"
        }
    },
    {
        "driverDetails": {
            "uuid": "4cd34747-1721-4553-84d4-59f53aaad736",
            "givenName": "Liam",
            "familyName": "Lawson",
            "familyNameFirst": false,
            "fullName": "Liam Lawson",
            "routePart": "liam-lawson-4cd34747"
        }
    },
    {
        "driverDetails": {
            "uuid": "3e7ffe41-e39f-41dc-94b6-6a098988481a",
            "givenName": "Oliver",
            "familyName": "Bearman",
            "familyNameFirst": false,
            "fullName": "Oliver Bearman",
            "routePart": "oliver-bearman-3e7ffe41"
        }
    },
    {
        "driverDetails": {
            "uuid": "0137527c-0f96-4af9-8976-19f27295fd96",
            "givenName": "Jack",
            "familyName": "Doohan",
            "familyNameFirst": false,
            "fullName": "Jack Doohan",
            "routePart": "jack-doohan-0137527c"
        }
    },
    {
        "driverDetails": {
            "uuid": "5a46fe0e-7e7d-414b-8f28-aadeab10ac77",
            "givenName": "Franco",
            "familyName": "Colapinto",
            "familyNameFirst": false,
            "fullName": "Franco Colapinto",
            "routePart": "franco-colapinto-5a46fe0e"
        }
    },
    {
        "driverDetails": {
            "uuid": "9d2459fb-5889-4cd7-abc6-12004a58a238",
            "givenName": "Gabriel",
            "familyName": "Bortoleto",
            "familyNameFirst": false,
            "fullName": "Gabriel Bortoleto",
            "routePart": "gabriel-bortoleto-9d2459fb"
        }
    },
    {
        "driverDetails": {
            "uuid": "4b849785-8eb1-41af-b87f-8da998d06c2b",
            "givenName": "Andrea Kimi",
            "familyName": "Antonelli",
            "familyNameFirst": false,
            "fullName": "Andrea Kimi Antonelli",
            "routePart": "andrea-kimi antonelli-4b849785"
        }
    },
    {
        "driverDetails": {
            "uuid": "95701466-d225-4921-aea6-c6615546d37e",
            "givenName": "Isack",
            "familyName": "Hadjar",
            "familyNameFirst": false,
            "fullName": "Isack Hadjar",
            "routePart": "isack-hadjar-95701466"
        }
    }
];
export default result;
